### ISSUE TITLE
apollo starter template

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#17]
## Tasks
- [x] migrate to apollo-server from voyager-server. Templates using voyager server will have complex use cases.
- [x] change current template from javascript to typescript
- [x] describe template structure
