### ISSUE TITLE
Create project proposal and architecture

### ISSUE THREAD

**Issue by ankitjena** [aerogear/graphback#3]
## ROADMAP
- [ ] Work on refining queries and resolver generation.
- [ ] Develop CLI for scaffolding project structure with template options.
- [ ] Provide OpenShift templates.

## ARCHITECTURE
TODO

**Comment by ankitjena** [comment]
Yes sure
