### ISSUE TITLE
Graphback Roadmap

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#317]
## Motivation

Roadmap for the RC1 release.
See: https://github.com/aerogear/graphback/issues/336

## Things to cover

- [x] OpenApi Generation
- [x] GraphQL resolver generation
- [x] Generation of the GraphQL Schema and Resolvers
- [x] Ability to work with existing templates using graphql-config
- [x] Integration with GraphQL CLI
- [x] Integration with GraphQL modules for data access layer 
- [x] Website improvements 
- [x] Service based architecture https://github.com/aerogear/graphback/issues/336
- [x] Database management #381 

## Architecture

GraphQL model (source) can be represented as a number of files where each of those will be processed by number of GraphQL code generator plugins:

- Schema generator ( generates schema from schema model )
- Resolver generator (generates thin layer of resolvers - can exist in many flavors like typescript/js etc.)
- DataServices generator generates data access logic - can exist with many flavours like knex, mongodb
- DB layer using graphql inspector to detect changes and apply them to database.
Migration tool will be always specific for the database

![Screenshot 2019-09-12 at 15 13 16](https://user-images.githubusercontent.com/981838/64791608-df8a9c00-d56f-11e9-9ebc-a49f9313aa7c.png)

### New Generator architecture that will cater to more generic use cases

https://github.com/aerogear/graphback/issues/336

### Migrations: OpenAPI to GraphQL 

Very good and proven library that generates GraphQL schema and resolvers. 
Schema supports various and complex api definitions.
Resolver layer is kinda complex but there is option to provide a custom one. 
Currently, we are using this library to output actual schema files that can be edited by users.
The reason for that is custom methods can overlap with CRUD ones. 

### Migrations: Database

Migrations to/from database 

https://github.com/aerogear/graphback/issues/318

### Performance

Using DataLoader layer together with GraphQL modules

## New Architecture investigations

I think we need to come up with new architecture that maps all the moving parts of the system

- Input sources (GraphQL Schema, OpenAPI, JSONSchema etc.)
- Modules (GraphQL module per each model file for separation of concerns) 
https://graphql-modules.com/
- Abstraction for data access logic. (DataServices type that can be DB(many subtypes) and REST
- Middleware type that can be REST, GraphQL (also with different subtypes)
- Tooling - Code Generation, validation, custom logic orchestration
- Transform templates to reference implementation (instead of many templates we can have single reference/opiniated server that is performant and production-ready - however community
should be able to build more
- Configuration - actual stack should be question-based (using new `graphback config` and `graphback init` command)
- People should be able to continue and tweak things using configurations

## Targets 

- Have clear responsibility for every layer of the subsystem
- Reuse a lot of proven open source technologies and standards as possible
- Decouple from template creation

## Challenges

- Source code promotion (dev/prod) on runtime
- Database migrations (depending on the db spike)
