### ISSUE TITLE
Graphback ROADMAP 1.0 beta

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#566]
## ROADMAP

Stabilize Graphback and improve general documentation and client side integrations

- [x] Plugin based architecture
- [x] Increase the number of integration tests #558 
- [x] Blog post on new Graphback architecture
- [x] Docs updates
- [x] Resolve all major bugs around around client side and relationships
- [x] Client side integration (Offline/Offix) https://github.com/aerogear/datasync/issues/233

**Comment by binayakbehera999** [comment]
Hi @wtrocki. I would like to contribute to this project. Could you suggest which issue to get started with and focus on?

**Comment by wtrocki** [comment]
@binayakbehera999 To avoid chatting on roadmap issue - please join our discord channel:

https://discordapp.com/invite/mJ7j84m

**Comment by wtrocki** [comment]
All targets are there. Closing
