### ISSUE TITLE
Docs issues

### ISSUE THREAD

**Issue by wtrocki** [aerogear/graphback#888]
1) Database migrations do not mention that they are only for postgress.
https://graphback.dev/docs/intro/concepts#database-migrations

2) https://graphback.dev/docs/intro/datamodel needs to be extended. 

A simple use case is needed.
Then follow up an example with relationships.
Then we might bring some table mapping and id annotations

Generally, people should be able to get a sense how to create most of the model use cases in less than 5 minutes

3) https://graphback.dev/docs/intro/config

Config - Db migrations should mention that they work only with Postgress data source and for MongoDB there is no need to have DB migrations section at all. 

4) https://graphback.dev/docs/intro/usecases

4rd use case should be added mention graphql serve

## Tasks

- [x] Database migrations do not mention that they are only for postgres.
- [x] graphback.dev/docs/intro/datamodel needs to be extended.
- [x] Config - Db migrations should mention that they work only with Postgress data source and for MongoDB there is no need to have DB migrations section at all. 
- [ ] Add use case for graphql-serve
- [ ] graphback.dev/docs/plugins/crud-resolvers Plugin mentions runtime. We should link to examples rather than putting this into plugin
- [ ] graphback.dev/docs/db/datasources - is in wrong chapter
Database chapter can be renamed to Database migrations
- [ ] Migrating to Graphback -> Migrating from REST

**Comment by craicoverflow** [comment]
I don't see much value in the [`Getting Started > Concepts`](https://graphback.dev/docs/intro/concepts#database-migrations) page. The sections do highlight some nice things about Graphback, but for someone looking to just **use** Graphback they might not be that important.

Plugins are useful to bring custom stuff but many people won't need to ever add one.
The same goes for **Graphback CRUD Runtime** here. It doesn't tell me anything I absolutely need to know to get started.
Database migrations are not needed by everyone necessarily, and this section does not add anything more than what is specified in `What is Graphback > What Graphback can do for you?`.
**Integration with existing GraphQL Ecosystem** is also  a nice to know fact for some people, but not for most.

The whole page is not needed in my opinion. With a well thought out sidebar users can see that we have Plugins, Database Migrations, CRUD spec from the link titles and click them as they need to use them.

**Comment by wtrocki** [comment]
1) https://graphback.dev/docs/plugins/crud-resolvers
Plugin mentions runtime. We should link to examples rather than putting this into plugin

**Comment by wtrocki** [comment]
This can be removed: https://graphback.dev/docs/crud/crudmapping

**Comment by wtrocki** [comment]
https://graphback.dev/docs/db/dbintroduction - We should reference that we support Postgres only

**Comment by wtrocki** [comment]
https://graphback.dev/docs/db/datasources - is in wrong chapter 
Database chapter can be renamed to `Database migrations`

**Comment by wtrocki** [comment]
`Migrating to Graphback` -> `Migrating from REST`

**Comment by craicoverflow** [comment]
> `Migrating to Graphback` -> `Migrating from REST`

So right now this makes sense as we only have information for how to migrate from REST. Will we be looking to add sections in the future for Migrating from Prisma, AppSync etc?

**Comment by wtrocki** [comment]
Yep. GraphQL Mesh could be good to get numbers of migrations

**Comment by craicoverflow** [comment]
> [graphback.dev/docs/db/datasources](https://graphback.dev/docs/db/datasources) - is in wrong chapter

Hmm where do you think this should be?
